services:
  backend:
    build:
      context: ./BackEnd/ogani
      dockerfile: Dockerfile
    container_name: ogani-backend
    ports:
      - "1999:1999"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.1.46:5432/ogani
      SPRING_DATASOURCE_USERNAME: novax
      SPRING_DATASOURCE_PASSWORD: Novax20250709
      UPLOAD_DIR: /app/src/main/resources/static/photos/
  # Angular Frontend
  frontend:
    build:
      context: ./FrontEnd/ogani
      dockerfile: Dockerfile
    container_name: ogani-frontend
    ports:
      - "5361:5361"
