# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ogani
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080

# ===============================
# GEMINI CONFIGURATION
# ===============================
gemini.api-key=AIzaSyAom_ETWIXweqceGQ93AooEru9qgKr2dEQ
gemini.model=gemini-2.5-flash-lite

# ===============================
# PAYOS CONFIGURATION
# ===============================
payos.client-id=f92633f2-107f-49cd-85c4-76e69cc0ffb9
payos.api-key=12a747b0-20bb-4111-824f-defa4c5490d0
payos.checksum-key=364a7d035ac3529ebdf133392b83fb232fb70307e6c8487ee82e4e357286b0a1
# ===============================
# JWT CONFIGURATION
# ===============================
jwtSecret=Qsrkd9ZO6Sf8GpKsg5mhoyF59GbcvAiXSVBiD5_FOwRtVbZPEAHGHLNLuApHjYJCWjnR8YfJO8fLjwsF2GSJqQ
jwtExpirationMs=86400000
jwtCookieName=jwtToken

# ===============================
# MULTIPART FILE UPLOAD CONFIGURATION
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# EMAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quyenquy053@gmail.com
spring.mail.password=ofgpgigbniiqzykn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.paypal=DEBUG

# ===============================
# SWAGGER CONFIGURATION
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
logging.level.org.springdoc=DEBUG

# ===============================
# GOOGLE OAUTH2 CONFIGURATION 
# ===============================
spring.security.oauth2.client.registration.google.client-id=877730433591-l46onaildrv7foqgr0flfomkiup80aic.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# ===============================
# SESSION CONFIGURATION
# ===============================
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true
server.servlet.session.timeout=86400

 

# ===============================
# OTHER CONFIGURATION
# ===============================
spring.main.allow-circular-references=true
